# Generated by Django 4.0.3 on 2022-11-21 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='short_desc',
            field=models.CharField(default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
