# Generated by Django 4.0.3 on 2022-11-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_short_desc_game_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': '游戏标签',
                'verbose_name_plural': '游戏标签',
            },
        ),
        migrations.RemoveField(
            model_name='game',
            name='tag',
        ),
        migrations.AddField(
            model_name='game',
            name='tags',
            field=models.ManyToManyField(to='games.gametag'),
        ),
    ]
