# Generated by Django 4.0.3 on 2022-03-15 13:45

from django.db import migrations, models
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('identification', models.FileField(upload_to=pathlib.PureWindowsPath('D:/PycharmProjects/2022-03/CapLink/identifications/identifications'))),
                ('address_proof', models.FileField(upload_to=pathlib.PureWindowsPath('D:/PycharmProjects/2022-03/CapLink/identifications/addressproof'))),
                ('is_success', models.BooleanField(default=False)),
            ],
        ),
    ]
