# Generated by Django 4.0.3 on 2022-03-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aml',
            old_name='location',
            new_name='address',
        ),
        migrations.AddField(
            model_name='aml',
            name='country',
            field=models.CharField(choices=[('USA', 'USA'), ('CHINA', 'CHINA')], default='123', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aml',
            name='post_code',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
    ]
