# Generated by Django 4.0.3 on 2022-03-16 12:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0002_rename_location_aml_address_aml_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aml',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aml',
            name='address_proof',
            field=models.FileField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='aml',
            name='identification',
            field=models.FileField(upload_to=''),
        ),
    ]
