# Generated by Django 4.0.3 on 2022-03-19 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('longth', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('hash_rate', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('power', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('efficiency', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('price', models.DecimalField(decimal_places=4, max_digits=9)),
                ('stock', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('sold', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('electricity_fee', models.DecimalField(decimal_places=4, max_digits=9)),
                ('hashrate_fee', models.DecimalField(decimal_places=4, max_digits=9)),
                ('service_fee', models.DecimalField(decimal_places=4, max_digits=9)),
                ('static_revenue_rate', models.FloatField()),
                ('img', models.ImageField(upload_to='projects')),
                ('details', models.TextField()),
                ('disclaimers', models.TextField()),
                ('faqs', models.ManyToManyField(blank=True, to='project.faq')),
            ],
        ),
    ]
