# Generated by Django 4.0.3 on 2022-03-27 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_faqcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='faq',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.faqcategory'),
            preserve_default=False,
        ),
    ]
